# Generated by Django 4.1 on 2022-10-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='musico_id',
            new_name='musico',
        ),
    ]
